# Use DecapBridge PKCE auth
backend:
  name: git-gateway
  repo: chromaglow/Nina
  branch: master
  auth_type: pkce
  base_url: https://auth.decapbridge.com
  auth_endpoint: /sites/6ccf8a10-ea7c-400d-9832-78f137623315/pkce
  auth_token_endpoint: /sites/6ccf8a10-ea7c-400d-9832-78f137623315/token
  gateway_url: https://gateway.decapbridge.com
  commit_messages:
    create: Create {{collection}} "{{slug}}" - {{author-name}} <{{author-login}}> via DecapBridge
    update: Update {{collection}} "{{slug}}" - {{author-name}} <{{author-login}}> via DecapBridge
    delete: Delete {{collection}} "{{slug}}" - {{author-name}} <{{author-login}}> via DecapBridge
    uploadMedia: Upload "{{path}}" - {{author-name}} <{{author-login}}> via DecapBridge
    deleteMedia: Delete "{{path}}" - {{author-name}} <{{author-login}}> via DecapBridge

logo_url: https://decapbridge.com/decapcms-with-bridge.svg
site_url: https://nintron.com

media_folder: src/assets/images/art
public_folder: ../../assets/images/art

collections:
  - name: "projects"
    label: "Gallery"
    folder: "src/content/projects"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Medium", name: "medium", widget: "string", required: false }
      - { label: "Year", name: "year", widget: "number", required: false }
      - { label: "Publish Date", name: "publishDate", widget: "datetime" }
      - { label: "Featured", name: "isFeatured", widget: "boolean", default: false }
      - label: "SEO Image"
        name: "seo"
        widget: "object"
        required: false
        fields:
          - label: "Image"
            name: "image"
            widget: "object"
            required: false
            fields:
              - { label: "Image", name: "src", widget: "image", required: false }
              - { label: "Alt text", name: "alt", widget: "string", required: false }
      - { label: "Description", name: "body", widget: "markdown", required: false }

  - name: "blog"
    label: "Journal"
    folder: "src/content/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Excerpt", name: "excerpt", widget: "string", required: false }
      - { label: "Publish Date", name: "publishDate", widget: "datetime" }
      - { label: "Featured", name: "isFeatured", widget: "boolean", default: false }
      - { label: "Tags", name: "tags", widget: "list", required: false }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "pages"
    label: "Pages"
    folder: "src/content/pages"
    create: false
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
